const express = require('express');
const router = express.Router();
const auth = require('../middleware/auth');
const Cart = require('../models/Cart');

// @route   GET api/cart
// @desc    Get user cart
// @access  Private
router.get('/', auth, async (req, res) => {
    try {
        let cart = await Cart.findOne({ user: req.user.id });
        if (!cart) {
            cart = new Cart({ user: req.user.id, items: [] });
            await cart.save();
        }
        res.json(cart.items);
    } catch (err) {
        console.error(err.message);
        res.status(500).send(err.message);
    }
});

// @route   POST api/cart
// @desc    Add item to cart
// @access  Private
router.post('/', auth, async (req, res) => {
    try {
        const newItem = req.body;
        
        let cart = await Cart.findOne({ user: req.user.id });
        if (!cart) {
            cart = new Cart({ user: req.user.id, items: [] });
        }

        // Check if item exists
        const itemIndex = cart.items.findIndex(item => item.title === newItem.title);

        if (itemIndex > -1) {
            // Product exists in the cart, update the quantity
            cart.items[itemIndex].quantity += 1;
        } else {
            // Product does not exists in cart, add new item
            cart.items.push({ ...newItem, quantity: 1 });
        }

        await cart.save();

        res.json(cart.items);
    } catch (err) {
        console.error(err.message);
        res.status(500).send(err.message);
    }
});

// @route   DELETE api/cart/:userId (Technically we should delete by Item ID, but current frontend uses index. 
// Implementation Strategy: Client sends the updated cart? Or we delete by ID if we add IDs to items.
// Simplest given current frontend state (array index): 
// We should probably rely on the ID generated by Mongoose for subdocuments!
// Mongoose adds _id to subdocs by default.
// Let's rely on Mongoose _id for deletion.

// @route   DELETE api/cart/:itemId
// @desc    Remove item from cart
// @access  Private
router.delete('/:itemId', auth, async (req, res) => {
    try {
        let cart = await Cart.findOne({ user: req.user.id });
        if (!cart) {
            return res.status(404).json({ msg: 'Cart not found' });
        }

        // Pull item by _id
        const removeIndex = cart.items.map(item => item.id).indexOf(req.params.itemId);

        if (removeIndex === -1) {
             // Fallback: If not found by ID (maybe old data), try matching simple props? 
             // No, let's assume valid ID.
             return res.status(404).json({ msg: 'Item not found' });
        }
        
        cart.items.splice(removeIndex, 1);
        await cart.save();

        res.json(cart.items);
    } catch (err) {
        console.error(err.message);
        res.status(500).send(err.message);
    }
});

module.exports = router;
